import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'
import { enableAutoUnmount, flushPromises, mount } from '@vue/test-utils'
import ModelIdentityView from '../ModelIdentityView.vue'
import IdentityRecentRuns from '@/components/admin/account/IdentityRecentRuns.vue'
import Select from '@/components/common/Select.vue'
import type { IdentityRun } from '@/api/admin/modelIdentity'

const mocks = vi.hoisted(() => ({ accounts: vi.fn(), account: vi.fn(), users: vi.fn(), user: vi.fn(), groups: vi.fn(), config: vi.fn(), saveConfig: vi.fn(), models: vi.fn(), savePlan: vi.fn(), updatePlan: vi.fn(), deletePlan: vi.fn(), plans: vi.fn(), history: vi.fn(), run: vi.fn(), cancel: vi.fn(), runStatus: vi.fn(), settings: vi.fn(), saveSettings: vi.fn(), plannedAccounts: vi.fn() }))
vi.mock('@/api/admin', () => ({ adminAPI: { accounts: { list: mocks.accounts, getById: mocks.account }, users: { list: mocks.users, getById: mocks.user }, groups: { getAll: mocks.groups } } }))
vi.mock('@/api/admin/modelIdentity', () => mocks)
vi.mock('vue-i18n', async (importOriginal) => ({ ...await importOriginal<typeof import('vue-i18n')>(), useI18n: () => ({ t: (key: string) => key, locale: { value: 'zh' } }) }))
vi.mock('@/components/layout/AppLayout.vue', () => ({ default: { template: '<div><slot /></div>' } }))
enableAutoUnmount(afterEach)
const account = { id: 18, name: 'Fixture account', platform: 'openai', group_ids: [7] }
const configuration = { account_id: 18, user_id: 5, group_id: 7, api_key_id: 9, key_name: '模型身份测试专用｜Fixture group｜Fixture account (#18)' }
const plan = { id: 1, account_id: 18, request_model: 'gpt-6-astra', expected_model: 'openai/gpt-6-astra', enabled: true, interval_minutes: 120, next_run_at: '2026-10-10T12:00:00Z' }
const runs: IdentityRun[] = Array.from({ length: 6 }, (_, i) => ({ id: i + 1, plan_id: 1, status: 'completed', created_at: `2026-10-10T0${i}:00:00Z`, request_model: 'gpt-6-astra', expected_model: 'openai/gpt-6-astra', report: { verdict: i === 5 ? 'mismatched' : 'matched', detected_model: i === 5 ? 'openai/gpt-5.5' : 'openai/gpt-6-astra' } }))
function open() { return mount(ModelIdentityView, { global: { stubs: { AppLayout: { template: '<div><slot /></div>' }, BaseDialog: { props: ['show'], template: '<section v-if="show"><slot /></section>' }, Icon: true, Pagination: true } } }) }
describe('model identity account matrix', () => {
  beforeEach(() => {
    vi.resetAllMocks()
    mocks.settings.mockResolvedValue({ public_base_url: '' })
    mocks.plannedAccounts.mockResolvedValue({ account_ids: [18], total: 1 })
    mocks.saveSettings.mockImplementation(async (value: { public_base_url: string }) => value)
    mocks.accounts.mockResolvedValue({ items: [account], total: 1 }); mocks.account.mockResolvedValue(account)
    mocks.users.mockResolvedValue({ items: [{ id: 5, username: 'Fixture user' }], total: 1 }); mocks.models.mockResolvedValue({ models: [{ id: 'openai/gpt-6-astra', name: 'openai/gpt-6-astra', family: 'openai' }] })
    mocks.saveConfig.mockResolvedValue(configuration); mocks.savePlan.mockResolvedValue(plan)
    mocks.groups.mockResolvedValue([{ id: 7, name: 'Fixture group', platform: 'openai' }])
    mocks.config.mockResolvedValue(configuration); mocks.plans.mockResolvedValue([plan]); mocks.history.mockResolvedValue(runs)
    mocks.runStatus.mockImplementation(async (id: number) => runs.find(run => run.id === id))
  })
  it('keeps Base URL editing open and marks it configured only after a successful explicit save', async () => {
    const w = open(); await flushPromises()
    const details = w.get('details')
    expect((details.element as HTMLDetailsElement).open).toBe(true)
    await w.get('#identity-base-url').setValue('h')
    expect((details.element as HTMLDetailsElement).open).toBe(true)
    expect(details.get('summary').text()).toContain('admin.modelIdentity.settingsUnsaved')
    expect(details.get('summary').text()).not.toContain('admin.modelIdentity.settingsConfigured')
    expect(mocks.saveSettings).not.toHaveBeenCalled()
    await w.get('#identity-base-url').setValue('https://site.example.com')
    expect((details.element as HTMLDetailsElement).open).toBe(true)
    expect(details.get('button[type="submit"]').attributes('disabled')).toBeUndefined()
    mocks.saveSettings.mockRejectedValueOnce(new Error('save failed'))
    await details.get('form').trigger('submit'); await flushPromises()
    expect((details.element as HTMLDetailsElement).open).toBe(true)
    expect(details.get('summary').text()).not.toContain('admin.modelIdentity.settingsConfigured')
    await details.get('form').trigger('submit'); await flushPromises()
    expect(details.get('summary').text()).toContain('admin.modelIdentity.settingsConfigured')
    expect((details.element as HTMLDetailsElement).open).toBe(true)
    // Native details toggles must survive subsequent edits/reactive renders.
    ;(details.element as HTMLDetailsElement).open = false
    await details.trigger('toggle')
    ;(details.element as HTMLDetailsElement).open = true
    await details.trigger('toggle')
    await w.get('#identity-base-url').setValue('https://changed.example.com')
    expect((details.element as HTMLDetailsElement).open).toBe(true)
    expect(details.get('summary').text()).toContain('admin.modelIdentity.settingsUnsaved')
  })
  it('loads and saves the site Base URL with feedback and no browser origin inference', async () => {
    mocks.settings.mockResolvedValue({ public_base_url: 'https://site.example.com/prefix' })
    const w = open(); await flushPromises()
    expect((w.get('#identity-base-url').element as HTMLInputElement).value).toBe('https://site.example.com/prefix')
    await w.get('#identity-base-url').setValue('https://new.example.com')
    await w.get('form').trigger('submit'); await flushPromises()
    expect(mocks.saveSettings).toHaveBeenCalledWith({ public_base_url: 'https://new.example.com' })
    expect(w.get('#identity-base-url-feedback').text()).toContain('admin.modelIdentity.settingsSaved')
    await w.get('#identity-base-url').setValue('https://another.example.com')
    expect(w.get('#identity-base-url-feedback').text()).not.toContain('admin.modelIdentity.settingsSaved')
    mocks.saveSettings.mockRejectedValue(new Error('HTTPS URL required'))
    await w.get('form').trigger('submit'); await flushPromises()
    expect(w.get('#identity-base-url-feedback').attributes('role')).toBe('alert')
    expect(w.get('#identity-base-url-feedback').text()).toBe('HTTPS URL required')
  })
  it('shows the latest result and five timestamped recent runs, newest first', async () => {
    const w = open(); await flushPromises()
    const row = w.get('table tr[data-plan-id="1"]')
    expect(row.text()).toContain('Fixture group'); expect(row.text()).toContain('openai/gpt-5.5')
    const recent = row.findComponent(IdentityRecentRuns)
    expect(recent.props('runs').map((run: IdentityRun) => run.id)).toEqual([6, 5, 4, 3, 2])
    expect(recent.findAll('time')).toHaveLength(5)
    await recent.find('button').trigger('click'); await flushPromises()
    expect(mocks.runStatus).toHaveBeenCalledWith(6)
    expect(w.text()).toContain('openai/gpt-5.5')
  })
  it('separates multiple plans for one account and retains each plan’s own history', async () => {
    const secondPlan = { ...plan, id: 2, request_model: 'gpt-6-luna', expected_model: 'openai/gpt-6-luna', enabled: false }
    mocks.plans.mockResolvedValue([plan, secondPlan])
    // More recent runs for one plan must not displace the other plan's history.
    mocks.history.mockImplementation(async (id: number) => id === 1 ? Array.from({ length: 50 }, (_, i) => ({ ...runs[5], id: 100 + i, created_at: '2026-10-10T05:00:00Z' })) : [{ ...runs[0], id: 200, plan_id: 2, request_model: secondPlan.request_model, expected_model: secondPlan.expected_model, report: { verdict: 'matched', detected_model: secondPlan.expected_model } }])
    const w = open(); await flushPromises()
    expect(w.findAll('table tr[data-plan-id]')).toHaveLength(2)
    expect(w.get('table tr[data-plan-id="1"]').findComponent(IdentityRecentRuns).props('runs').every((run: IdentityRun) => run.plan_id === 1)).toBe(true)
    const second = w.get('table tr[data-plan-id="2"]')
    expect(second.text()).toContain('openai/gpt-6-luna')
    expect(second.text()).toContain('admin.modelIdentity.matched')
    expect(second.findComponent(IdentityRecentRuns).props('runs').map((run: IdentityRun) => run.id)).toEqual([200])
    await second.findAll('button').find(button => button.text() === 'admin.modelIdentity.manualTrigger')!.trigger('click'); await flushPromises()
    expect(mocks.run).toHaveBeenCalledWith(2)
  })
  it('keeps history below the plan and edits only that plan on the same form', async () => {
    const w = open(); await flushPromises()
    const row = w.get('table tr[data-plan-id="1"]')
    await row.findAll('button').find(button => button.text() === 'admin.modelIdentity.history')!.trigger('click')
    expect(row.element.nextElementSibling?.id).toBe('identity-history-1')
    await row.findAll('button').find(button => button.text() === 'common.edit')!.trigger('click'); await flushPromises()
    expect(w.findAllComponents(Select).find(select => select.props('id') === 'identity-add-account')!.props('disabled')).toBe(true)
    expect((w.get('#identity-add-model').element as HTMLInputElement).value).toBe(plan.request_model)
    await w.get('#identity-add-model').setValue('gpt-6-astra-alias')
    await w.findAll('form').find(form => form.find('#identity-add-model').exists())!.trigger('submit')
    await flushPromises()
    expect(mocks.updatePlan).toHaveBeenCalledWith(1, expect.objectContaining({ request_model: 'gpt-6-astra-alias' }))
    expect(mocks.savePlan).not.toHaveBeenCalled()
    expect(mocks.saveConfig).not.toHaveBeenCalled()
  })
  it('hydrates the configured test user outside the first search page', async () => {
    mocks.users.mockResolvedValue({ items: [], total: 30 })
    mocks.user.mockResolvedValue({ id: 5, username: 'Configured user' })
    const w = open(); await flushPromises()
    await w.get('table tr[data-plan-id="1"]').findAll('button').find(button => button.text() === 'common.edit')!.trigger('click'); await flushPromises()
    expect(mocks.user).toHaveBeenCalledWith(5)
    expect(w.findAllComponents(Select).find(select => select.props('id') === 'identity-add-user')!.props('options')).toEqual([{ value: 5, label: 'Configured user (#5)' }])
  })
  it('lists only planned accounts and configures a new plan on one page', async () => {
    mocks.plannedAccounts.mockResolvedValue({ account_ids: [], total: 0 })
    mocks.config.mockRejectedValue({ status: 404 })
    const w = open(); await flushPromises()
    expect(mocks.accounts).not.toHaveBeenCalled()
    expect(w.findAll('[data-plan-id]')).toHaveLength(0)
    expect(w.text()).toContain('admin.modelIdentity.emptyPlans')
    await w.findAll('button').find(button => button.text().includes('admin.modelIdentity.addPlan'))!.trigger('click'); await flushPromises()
    expect(mocks.accounts).toHaveBeenCalledWith(1, 50, { lite: 'true', search: '' })
    const chooser = w.findAllComponents(Select).find(select => select.props('id') === 'identity-add-account')!
    expect(chooser.props('options')).toEqual([{ value: 18, label: 'Fixture account (#18)' }])
    chooser.vm.$emit('update:modelValue', 18)
    await flushPromises()
    w.findAllComponents(Select).find(select => select.props('id') === 'identity-add-user')!.vm.$emit('update:modelValue', 5)
    await w.findAll('select').find(select => select.text().includes('Fixture group'))!.setValue(7)
    await w.findAll('select').find(select => select.text().includes('openai/gpt-6-astra'))!.setValue('openai/gpt-6-astra')
    const addForm = w.findAll('form').find(form => form.text().includes('admin.modelIdentity.addPlan'))!
    await w.get('#identity-add-model').setValue('gpt-6-astra')
    expect(addForm.text()).not.toContain('common.next')
    await addForm.trigger('submit'); await flushPromises()
    expect(mocks.saveConfig).toHaveBeenCalledWith(18, { user_id: 5, group_id: 7 })
    expect(mocks.savePlan).toHaveBeenCalledWith(expect.objectContaining({ account_id: 18, request_model: 'gpt-6-astra' }))
  })
  it('never substitutes demo accounts when the account API fails', async () => {
    mocks.plannedAccounts.mockRejectedValue(new Error('API unavailable'))
    const w = open(); await flushPromises()
    expect(w.get('[role="alert"]').text()).toContain('API unavailable')
    expect(w.findAll('[data-plan-id]')).toHaveLength(0)
    expect(w.text()).not.toContain('OpenAI 主账号')
  })
  it('distinguishes missing configuration from history or service failures', async () => {
    mocks.config.mockRejectedValue({ status: 404 })
    const w = open(); await flushPromises()
    expect(w.findAll('[data-plan-id]')).toHaveLength(0)
    expect(mocks.history).not.toHaveBeenCalled()
    mocks.config.mockResolvedValue(configuration); mocks.history.mockRejectedValue(new Error('history failed'))
    await w.findAll('button').find(button => button.text() === 'common.refresh')!.trigger('click'); await flushPromises()
    expect(w.get('table tr[data-plan-id="1"]').text()).toContain('admin.modelIdentity.service_error')
  })
  it('preserves request failure status and sends a manual run to the selected plan', async () => {
    mocks.history.mockResolvedValue([{ ...runs[5], status: 'request_error', report: { verdict: 'inconclusive' } }])
    const w = open(); await flushPromises(); const row = w.get('table tr[data-plan-id="1"]')
    expect(row.text()).toContain('admin.modelIdentity.request_error')
    await row.findAll('button').find(button => button.text() === 'admin.modelIdentity.manualTrigger')!.trigger('click'); await flushPromises()
    expect(mocks.run).toHaveBeenCalledWith(1)
  })
})
